# -------------------------------------------- #
# Note: this file originates in template-shell #
# -------------------------------------------- #

name: push

on:
  - push
  - workflow_dispatch

permissions: read-all

jobs:
  main:
    uses: ahmadnassri/actions/.github/workflows/push-shell.yml@master
    secrets: inherit
    permissions:
      contents: write
      statuses: write
      pull-requests: write
